### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by ilyosdev** [joeldevelops/reports-backend#6]
You know nestjs. But why are you using express?

**Comment by joeldevelops** [comment]
NestJS uses express under the hood. The important distinction to understand between the two:
- Express is a web framework, it enables you to serve web traffic via APIs.
- NestJS is an application-level framework that provides "plug and play" integrations and opinionated design decisions. One such integration is web traffic via express.

More importantly, Nest is OOP-focused and styled to look like an angular application. While there is nothing wrong with this, OOP doesn't really offer many benefits for a nodeJS application due to classes being broken ('this' is broken in Javascript, typescript only kind of fixes this). For this reason, if I wanted to do OOP and a class-based webserver, I would be better off to just use another language that works better with classes and is faster (Java, C#, etc.). Instead, I prefer a more functional approach for this service as it improves the testability of the code.

However, the design of this application does not call for any over-the-top integrations (RMQ, GraphQL, etc) or techniques (module lazy-loading, dependency injection, ect). So by having no need for most of the features or approaches that NestJS supplies, it would be superfluous to include it and would only make the codebase needlessly complex.

The takeaway from this should be the following two things:
- By designing your services upfront, you will know what kinds of integrations you need and can make a decision about wether you need an application-level framework or not.
- When deciding which language to use for a solution, you should take into account the strengths of that language and use those strengths when designing and implementing that language. (For instance, Java provides strong type safety but can be brittle in the face of constantly changing or uncertain API contracts, whereas JS or Python can handle type uncertainty quite well)

With all of this in mind it is still good to know how to use NestJS 🚀

**Comment by ilyosdev** [comment]
Wow, thanks you for taking your time to explain it. It means a lot

**Comment by joeldevelops** [comment]
Glad to help!
